build_platform:
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
noarch_platforms:
  - linux_64
  - win_64
provider:
  linux_aarch64: default
  linux_ppc64le: default
test: native_and_emulated
